# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Project EPIC - Empowering the Public with Information in Crisis
tagline: Empowering the Public with Information in Crisis
author :
  twitter : epiccolorado

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.

production_url : project-epic.github.io

# prose config
prose:
  rooturl: '_posts'
  media: '_posts/images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes

google_info :
  press :
    key    : 0Aiwzrc8lx93KdEpoYlZPa2tRU25FT1Fzb2s4Yi16UlE
    object : Press
    types  : ['Press']

  people :
    key    : 0Aiwzrc8lx93KdDJrQllra3VmQkx1OTNlclNCY0hIWFE
    object : Person
    types  : ['Current', 'Alumni']

  projects :
    key    : 0AihuFDqjCvbedDMzS0FRc1hTT3JVY2lRT2pfekszY3c
    object : Project
    types  : ['Projects']
  publications :
    key    : 0Aiwzrc8lx93KdFhudDZDZzdRTkVHQWtpUVNFd01xckE
    object : Publication
    types  : ['Publications']

data_directory : './_data'

credentials: _secret_config.yml

JB:
  ASSET_PATH : false

  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change them here if needed.
  #
  archive_path: /news/archive.html
  categories_path : /categories.html
  tags_path : /tags.html
